spring:
  application:
    name: danieltrack-metrics-prometheus
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}